usb: gadget: fix compile break due to api change
Android changed the bind_config API and hence adapt the ethernet gadget:

Fixes following compile error:
drivers/usb/gadget/ether.c: In function 'rndis_do_config':
drivers/usb/gadget/ether.c:249: error: too few arguments to function 'rndis_bind_config'
make[3]: *** [drivers/usb/gadget/ether.o] Error 1

Signed-off-by: Vimarsh Zutshi <vimarsh.zutshi@ti.com>
Signed-off-by: Vikram Pandita <vikram.pandita@ti.com>