omap: usb: g_serial: include delay.h header
Fixes compilation error when the gadget serial
is compiled as module. A missing objects from
delay.h were not linked to the gadget serial
driver.

drivers/usb/gadget/composite.c:121:
error: implicit declaration of function 'msleep'
In file included from drivers/usb/gadget/u_serial.c:24,
                 from drivers/usb/gadget/serial.c:49:
include/linux/delay.h: At top level:
include/linux/delay.h:46: warning:
conflicting types for 'msleep'
drivers/usb/gadget/composite.c:121: note:
previous implicit declaration of 'msleep' was here
make[2]: *** [drivers/usb/gadget/serial.o] Error 1
make[1]: *** [drivers/usb/gadget] Error 2
make: *** [drivers] Error 2

Signed-off-by: Leed Aguilar <leed.aguilar@ti.com>