arch: x86: kernel: compile fix for its_static_thunk
  CC      arch/x86/kernel/alternative.o - due to target missing
arch/x86/kernel/alternative.c:1452:5: error: redefinition of its_static_thunk
 u8 *its_static_thunk(int reg)
     ^~~~~~~~~~~~~~~~
In file included from ./arch/x86/include/asm/barrier.h:5:0,
                 from ./include/linux/list.h:11,
                 from ./include/linux/module.h:12,
                 from arch/x86/kernel/alternative.c:4:
./arch/x86/include/asm/alternative.h:143:19: note: previous definition of its_static_thunk was here
 static inline u8 *its_static_thunk(int reg)
                   ^~~~~~~~~~~~~~~~
scripts/Makefile.build:244: recipe for target arch/x86/kernel/alternative.o failed

Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>