Revert "musb: omap2430: do not assume balanced enable()/disable()"
This reverts commit f874d424c8ecfb1c20b5b61eb04e462d9fb05e4e.

patch does no longer compile:

drivers/usb/musb/omap2430.c: In function 'omap2430_musb_disable':
drivers/usb/musb/omap2430.c:389:10: error: 'struct omap2430_glue' has no member named 'enabled'
  if (glue->enabled) {
          ^
make[4]: *** [drivers/usb/musb/omap2430.o] Error 1
make[3]: *** [drivers/usb/musb] Error 2
make[2]: *** [drivers/usb] Error 2
make[1]: *** [drivers] Error 2