board-omap3gta04: Fix section mismatch error.
Fix following:
arch/arm/mach-omap2/board-omap3gta04.c: At top level:
include/linux/init.h:239:20: error: __setup_str_gta04_init_bymux causes a section type conflict with usbhs_bdata

Fix also issue 468 (http://projects.goldelico.com/p/gta04-kernel/issues/468/)

Seems gcc dislike mixing const and non-const data in same section. __setup()
macro is const but usbhs_bdata cannot be const because it must be writable
(usbhs_init()) so move it to different section to fix issue.

Note: same section is used for usbhs_bdata in devkit800, omap3beagle boards..

Signed-off-by: Marek Belisko <marek@goldelico.com>