Revert "modpost: inform compilers that fatal() never returns"
This reverts commit 16a473f60edc30ffcdf355676263730a6028ec67.

It is broken on Darwin built host.

  HOSTCC  scripts/mod/modpost.o - due to target missing
scripts/mod/modpost.c:94:1: error: only weak aliases are supported in this configuration
   94 | modpost_log_noret(enum loglevel loglevel, const char *fmt, ...);
      | ^~~~~~~~~~~~~~~~~