DSPBRIDGE: checkpatch - space required before open parenthesis
ERROR: space required before the open parenthesis '('

Signed-off-by: Omar Ramirez Luna <omar.ramirez@ti.com>