ice: compile fix for health reporter code
static const char *const pointer = "string";
static const struct { const char *ptr; } var = { pointer };

does not work with gcc 6.3 because 'pointer' is not a constant initializer, even if
declared as such.

It is a memory location which is initialized to point to a different location (the "string").

Such code leads to:

test.c:15:31: error: initializer element is not constant
 const struct { char *ptr; } var = { pointer };
                                     ^~~~~~~
test.c:15:31: note: (near initialization for 'var.ptr')

Some compilers *may* be able to deduce that this are all constants and do what is indended.

The canonical way is to declare it differently:

static const char pointer[] = "string";
static const struct { const char *ptr; } var = { pointer };

And the same here in this file with ice_common_port_solutions in ice_health_status_lookup.

Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>