staging: rtl8189es: fix issue with struct sha256_state which is now also defined system wide
  CC [M]  drivers/staging/rtl8189es/core/rtw_br_ext.o - due to target missing
In file included from drivers/staging/rtl8189es/include/drv_types.h:87:0,
                 from drivers/staging/rtl8189es/core/rtw_br_ext.c:32:
drivers/staging/rtl8189es/include/rtw_security.h:241:8: error: redefinition of 'struct sha256_state'
 struct sha256_state {
        ^
In file included from ./include/linux/filter.h:23:0,
                 from ./include/net/sock.h:59,
                 from ./include/net/inet_sock.h:22,
                 from ./include/net/ip.h:27,
                 from drivers/staging/rtl8189es/core/rtw_br_ext.c:24:
./include/crypto/sha.h:84:8: note: originally defined here
 struct sha256_state {
        ^
make[5]: *** [drivers/staging/rtl8189es/core/rtw_br_ext.o] Error 1

Signed-off-by: H. Nikolaus Schaller <hns@goldelico.com>