OMAP5: PM: defconfig: fix compile break
rpmsg requires to have NET config enabled else following
compile break is see:

drivers/built-in.o: In function `alloc_skb':
include/linux/skbuff.h:515: undefined reference to `__alloc_skb'
drivers/built-in.o: In function `rpmsg_omx_cb':
drivers/rpmsg/rpmsg_omx.c:301: undefined reference to `skb_put'
drivers/rpmsg/rpmsg_omx.c:305: undefined reference to `skb_queue_tail'
drivers/built-in.o: In function `rpmsg_omx_read':
drivers/rpmsg/rpmsg_omx.c:576: undefined reference to `skb_dequeue'
drivers/rpmsg/rpmsg_omx.c:592: undefined reference to `kfree_skb'

Fixing this compile break with pm-defconfig

Signed-off-by: Vikram Pandita <vikram.pandita@ti.com>