rpmsg: build only if TI TILER is present
rpmsg_omx driver will eventually use ION, till then,
it depends on TI_TILER being configured in the system.

This fixes the build error:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
drivers/built-in.o: In function `_rpmsg_omx_map_buf':
drivers/rpmsg/rpmsg_omx.c:108: undefined reference to `tiler_virt2phys'
drivers/rpmsg/rpmsg_omx.c:117: undefined reference to `tiler_virt2phys'
make: *** [.tmp_vmlinux1] Error 1

Change-Id: I3a5f4aaa59714476a2f7902a2f216dd1e8a58af3
Signed-off-by: Nishanth Menon <nm@ti.com>
Signed-off-by: Suman Anna <s-anna@ti.com>