OMAP4: HSI: use static inline to prevent build breaks
When HSI driver is disabled, the kernel is still supposed to build and boot.
This is only possible if the inline functions are not global.
To fix, this, make the inline dummy functions as static

This fixes errors such as the following when HSI driver is disabled:
arch/arm/mach-omap2/board-omap5evm-modem.o: In function `omap_hsi_prepare_suspend':
/arch/arm/plat-omap/include/plat/omap_hsi.h:489: multiple definition of `omap_hsi_prepare_suspend'
arch/arm/mach-omap2/board-omap5evm.o:/arch/arm/plat-omap/include/plat/omap_hsi.h:489: first defined here
arch/arm/mach-omap2/board-omap5evm-modem.o: In function `omap_hsi_io_wakeup_check':
/arch/arm/plat-omap/include/plat/omap_hsi.h:490: multiple definition of `omap_hsi_io_wakeup_check'
arch/arm/mach-omap2/board-omap5evm.o:/arch/arm/plat-omap/include/plat/omap_hsi.h:490: first defined here
arch/arm/mach-omap2/board-omap5evm-modem.o: In function `omap_hsi_wakeup':
/arch/arm/plat-omap/include/plat/omap_hsi.h:491: multiple definition of `omap_hsi_wakeup'
arch/arm/mach-omap2/board-omap5evm.o:/arch/arm/plat-omap/include/plat/omap_hsi.h:491: first defined here
arch/arm/mach-omap2/board-omap5evm-modem.o: In function `omap_hsi_is_io_wakeup_from_hsi':
/arch/arm/plat-omap/include/plat/omap_hsi.h:492: multiple definition of `omap_hsi_is_io_wakeup_from_hsi'
arch/arm/mach-omap2/board-omap5evm.o:/arch/arm/plat-omap/include/plat/omap_hsi.h:492: first defined here
arch/arm/mach-omap2/board-omap5evm-modem.o: In function `omap_hsi_dev_init':
/arch/arm/plat-omap/include/plat/omap_hsi.h:493: multiple definition of `omap_hsi_dev_init'
arch/arm/mach-omap2/board-omap5evm.o:/arch/arm/plat-omap/include/plat/omap_hsi.h:493: first defined here

Change-Id: I2359ce1c773917ff207ffdf82437f31261899d52
Signed-off-by: Nishanth Menon <nm@ti.com>